- hosts: talos
  remote_user: ubuntu
  become: yes
  vars_files:
    vault-pass.yaml
  tasks:
    - name: connection success
      debug:
        msg: "user={{NEXUS_USER}} , pass={{NEXUS_PASS}} , HOST_IP={{192.168.44.129}} , commit-ID={{DOCKER_TAG}}
