- hosts: talos
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Build latest docker image
      command: docker build . -t bezardo/myweb:{{DOCKER_TAG}}
      args:
        chdir: /var/lib/jenkins/workspace/FinolaFIne Automata

    - name: Login to Nexus artifactory
      shell: echo ${NEXUS_PASS} | docker login -u ${NEXUS_USER} --password-stdin {{HOST_IP}}:8082

    - name: Tag the image
      shell: docker tag bezardo/myweb:{{DOCKER_TAG}} {{HOST_IP}}:8082/newapp:{{DOCKER_TAG}} 

    - name: Push the image to Nexus
      shell: docker push {{HOST_IP}}:8082/newapp:{{DOCKER_TAG}}

    - name: dynamically change image in deployment manifest
      shell: chmod +x changeTag.sh && ./changeTag.sh {{DOCKER_TAG}}

    - name: apply manifests
      shell: kubectl apply -f /var/lib/jenkins/workspace/FinolaFIne Automata/
